### Get Toxi Proxy Configuration
GET http://localhost:8474/proxies

### Configure Proxy
POST http://localhost:8474/populate

  [
    {
      "name": "payment",
      "listen": "0.0.0.0:8888",
      "upstream": "payment:8080",
      "enabled": true
    }
  ]

### set upstream-reset-peer toxic
POST http://localhost:8474/proxies/payment/toxics

        {
          "name": "reset-peer-upstream",
          "type": "reset_peer",
          "stream": "upstream",
          "toxicity": 0.3,
          "attributes": {
            "timeout": 1
          }
        }

### set downstream-reset-peer toxic
POST http://localhost:8474/proxies/payment/toxics

        {
          "name": "reset-peer-downstream",
          "type": "reset_peer",
          "stream": "downstream",
          "toxicity": 0.3,
          "attributes": {
            "timeout": 1
          }
        }

### reset toxi proxy

POST http://localhost:8474/reset

